export const LANGUAGE_OPTIONS = [
  ['ar', '阿拉伯语'],
  ['bg', '保加利亚语'],
  ['bn', '孟加拉语'],
  ['cs', '捷克语'],
  ['da', '丹麦语'],
  ['de', '德语'],
  ['el', '希腊语'],
  ['en', '英语'],
  ['es', '西班牙语'],
  ['fi', '芬兰语'],
  ['fr', '法语'],
  ['he', '希伯来语'],
  ['hi', '印地语'],
  ['hr', '克罗地亚语'],
  ['hu', '匈牙利语'],
  ['id', '印度尼西亚语'],
  ['it', '意大利语'],
  ['ja', '日语'],
  ['kn', '卡纳达语'],
  ['ko', '韩语'],
  ['lt', '立陶宛语'],
  ['mr', '马拉地语'],
  ['nl', '荷兰语'],
  ['no', '挪威语'],
  ['pl', '波兰语'],
  ['pt', '葡萄牙语'],
  ['ro', '罗马尼亚语'],
  ['ru', '俄语'],
  ['sk', '斯洛伐克语'],
  ['sl', '斯洛文尼亚语'],
  ['sv', '瑞典语'],
  ['ta', '泰米尔语'],
  ['te', '泰卢固语'],
  ['th', '泰语'],
  ['tr', '土耳其语'],
  ['uk', '乌克兰语'],
  ['vi', '越南语'],
  ['zh', '简体中文'],
  ['zh-Hant', '繁体中文'],
] as const

export function languageLabel(code: string): string {
  if (code === 'auto') return '自动检测'
  const option = LANGUAGE_OPTIONS.find(([value]) => value === code)
  return option ? `${option[1]} · ${option[0]}` : code
}
